### ISSUE TITLE
conflict with css -webkit-font-smoothing:antialiased

### ISSUE THREAD

**Issue by piskello** [tsurule/morelines#1]
Hi, thank you for this very useful js. I'm working on a project and I started using it, but for certain reasons, it didn't work properly. It opens perfectly but the closing-transition were missing. After some debug, it seems it's a conflict with the  -webkit-font-smoothing:antialiased property I was applying to all the divs in order to have a uniform font rendering among different browsers.

Hope it helps :)

**Comment by tsurule** [comment]
Hey, thanks for feedback @piskello .
Please can you help me with this issue, wanna figure out more detail with this.
Can you live here some fiddle 'http://jsfiddle.net/' or something?

Or clarify on which browsers you catch this issue. Sorry, for now can reproduce it :(

Thanks again for feedback! :)

**Comment by piskello** [comment]
Hi,  first of all: sorry for the delay. After some months I returned on the project and I discovered was my error.
