### ISSUE TITLE
How can I use it one resposive tab

### ISSUE THREAD

**Issue by rheman** [tsurule/morelines#2]
Hi,
Great plugin. But I have some troubles using it on responsive tab build using bootstrap.
I am using the following tab on my website . https://bootsnipp.com/snippets/featured/people-card-with-tabs
Your plugin works only on the first befault display tab. How can I use it on other tabs (tab which are not displayed by default) ?

Best regard.

**Comment by tsurule** [comment]
Hi @rheman ,

Thanks for feedback.

Need to figure out with that, have you some jsfiddle.net or codepen example? It's will be much better with that. My guess, is that the plugin not initialize in others tabs at all, it simply to detect it, if on others tabs do not appear plugin's wrapper, then plugin do not init on that's tabs, as I mentioned before.

Thanks, hope it will help.
T

**Comment by rheman** [comment]
Hi @tsurule  you are right, the plugin is not initialize in others tab at all. How can I initialize it in other tab ?

**Comment by tsurule** [comment]
Hi @rheman ,
Aha, so please, try something like this approach:

```
$('#myTab a[href="#location"]').one('shown.bs.tab', function (e) {
    $('.your-class').moreLines();
});
- or with data if you need -
$('a[data-toggle="tab"]').one('shown.bs.tab', function (e) {
    $('.your-class').moreLines();
});
- or try init plugin again by clicking -
 $('a[data-toggle="tab"]').click(function () {
    $(this).closest('.panel').find('.your-class').moreLines();
});
```
Hope it will help you.
Thanks,
T

**Comment by tsurule** [comment]
Hi @rheman ,

Is there any feedback? Can I close this issue? Hope my last comment help to resolve your case.

Thanks,
T

**Comment by rheman** [comment]
Thanks  a lot work perfectly
