### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by piskello** [tsurule/morelines#3]
Hello again :)
I'm wondering how to add a callback event once the full-text is displayed: do you have any suggestion?
Thank you in advance, 
Matteo

**Comment by tsurule** [comment]
Hey,
Sorry I have missed this message here.
Hmm, it depend what staff do you need implement. For now you can detect state by class, once text are expanded, on button appear class 'active'. That how you can check state. For for now I have not planning some modifications for this plugin. 

But if you wanna make extension for this - welcome for your pull request :)

That is good idea to work with, thanks :)

Vlad
